version: "2"
services:
  app:
    container_name: app
    restart: always
    build: ./appointment.service
    ports:
      - "3000:3000"
    links:
      - mongo2
    depends_on:
      - mongo2
    networks:
      - nodeapp-network

  email.service:
    container_name: email.service
    restart: always
    build: ./email.service
    ports:
      - "3001:3001"
    networks:
      - nodeapp-network

  mongo2:
    container_name: mongo2
    image: mongo
    # volumes:
    #   - ./data:/data/db
    # ports:
    #   - "27017:27017"
    networks:
      - nodeapp-network

networks:
  nodeapp-network:
    driver: bridge