using System;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
namespace customer.service.Model {
    public class CustomerModel {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }

        [BsonDateTimeOptions]
        public DateTime Created { get; set; }

    }
}